CREATE TABLE [dbo].[ANKET](
	[SatirId] [int] IDENTITY(1,1) NOT NULL,
	[Secim] [int] NULL,
	[Tarih] [datetime] NULL,
	[TerminalId] [int] NULL,
 CONSTRAINT [PK_ANKET] PRIMARY KEY CLUSTERED 
(
	[SatirId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


