CREATE TABLE [dbo].[FONTLAR](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[FONT] [nvarchar](100) NULL,
 CONSTRAINT [PK_FONTLAR] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

