CREATE TABLE [dbo].[HAVUZ](
	[SatirId] [int] IDENTITY(1,1) NOT NULL,
	[BID] [int] NULL,
	[TID] [int] NULL,
	[Tarih] [datetime] NULL,
 CONSTRAINT [PK_Havuz] PRIMARY KEY CLUSTERED 
(
	[SatirId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


