TRUNCATE TABLE anatablolar;
INSERT INTO `anatablolar` (`ATID`, `TABLO_ADI`, `TABLO_TURU`, `S_YF1`, `S_YF2`, `S_YF3`, `I_YF1`, `I_YF2`, `I_YF3`, `B_YF`) VALUES
(130, 'ANATABLO', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(131, 'EKRAN 1', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(132, 'EKRAN 2', 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL);