TRUNCATE TABLE `terminal_grup`;
INSERT INTO `terminal_grup` (`TGID`, `TID`, `GRPID`, `CAGRI_ORAN`, `TRANSFER_ORAN`, `YARDIM_GRUBU`, `CAGRILAN`, `TRANSFER_CAGRILAN`, `ONCELIK`, `S_YF1`, `S_YF2`, `S_YF3`, `I_YF1`, `I_YF2`, `I_YF3`, `B_YF`, `AYRICALIKLI`) VALUES
(1142, 74, 83, 1, 1, 0, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(1151, 76, 84, 1, 1, 0, 0, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);
