TRUNCATE TABLE anatablo_yon;
INSERT INTO anatablo_yon ([ATID], [TID], [YON], [S_YF1], [S_YF2], [S_YF3], [I_YF1], [I_YF2], [I_YF3], [B_YF], [Port]) VALUES
(130, 74, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0),
(130, 76, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0);