CREATE TABLE IF NOT EXISTS `butonlar` (
  `BM_ADRES` int(11) NOT NULL,
  `BTNID` int(11) NOT NULL,
  `GRP_ID` int(11) DEFAULT NULL,
  `ANA_BTNID` int(11) DEFAULT '0',
  `BTN_EKRAN` varchar(250) DEFAULT '',
  `BTN_BILET_S1` varchar(50) DEFAULT '',
  `BTN_BILET_S2` varchar(50) DEFAULT '',
  `BTN_BILET_S3` varchar(50) DEFAULT '',
  `BTN_BILET_S4` varchar(50) DEFAULT '',
  `MAKS_BILET` smallint(6) DEFAULT NULL,
  `BILET_KOPYA` smallint(6) DEFAULT '1',
  `YUKSEKLIK` smallint(6) DEFAULT NULL,
  `GENISLIK` smallint(6) DEFAULT NULL,
  `RENK` int(11) DEFAULT '0',
  `YAZI_RENGI` int(11) DEFAULT '0',
  `RESIM` longblob,
  `RESIM_YON` int(11) DEFAULT '32',
  `RESIM_AD` varchar(20) DEFAULT '',
  `ESKI_RESIM_AD` varchar(20) DEFAULT '',
  `ACIKLAMA` varchar(250) DEFAULT '',
  `AKTIF` tinyint(1) DEFAULT '1',
  `S_YF1` varchar(50) DEFAULT '',
  `S_YF2` varchar(50) DEFAULT '',
  `S_YF3` varchar(50) DEFAULT '',
  `I_YF1` int(11) DEFAULT NULL,
  `I_YF2` int(11) DEFAULT NULL,
  `I_YF3` int(11) DEFAULT NULL,
  `B_YF` tinyint(1) DEFAULT NULL,
  `RandevuButonuMu` tinyint(1) DEFAULT NULL,
  `GRP_ID2` int(11) DEFAULT NULL,
  `GRP1_ORAN` int(11) DEFAULT NULL,
  `GRP2_ORAN` int(11) DEFAULT NULL,
  `GRP_ID3` int(11) DEFAULT NULL,
  `GRP3_ORAN` int(11) DEFAULT NULL,
  `GRP_ID4` int(11) DEFAULT NULL,
  `GRP4_ORAN` int(11) DEFAULT NULL,
  `FONT` varchar(40) DEFAULT '',
  `PUNTO` smallint(6) DEFAULT NULL,
  `Border_Style` varchar(20) NOT NULL,
  `Border_Width` int(11) NOT NULL,
  `Border_Color` int(11) NOT NULL,
  `Border_Radius` int(11) NOT NULL,
  PRIMARY KEY (`BTNID`,`BM_ADRES`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER DATABASE `butonlar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;