CREATE TABLE IF NOT EXISTS `fontlar` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FONT` varchar(80) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8;
ALTER DATABASE `fontlar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;