CREATE TABLE IF NOT EXISTS `kiosk_ayar` (
  `KID` int(11) NOT NULL,
  `BASLIK` varchar(200) DEFAULT '',
  `ALT_BASLIK` varchar(200) DEFAULT '',
  `MESAJ_OGLE` varchar(50) DEFAULT '',
  `MESAJ_SISTEM_KAPALI` varchar(50) DEFAULT '',
  `MESAJ_SERVIS_KAPALI` varchar(50) DEFAULT '',
  `SOL_BTN_ADET` smallint(6) DEFAULT NULL,
  `SAG_BTN_ADET` smallint(6) DEFAULT NULL,
  `SOL_PADDING` smallint(6) DEFAULT NULL,
  `SAG_PADDING` smallint(6) DEFAULT NULL,
  `FONT` varchar(40) DEFAULT '',
  `PUNTO` smallint(6) DEFAULT NULL,
  `BTN_FONT` varchar(40) DEFAULT '',
  `BTN_PUNTO` smallint(6) DEFAULT NULL,
  `GECIKME` int(11) DEFAULT NULL,
  `YAZI_RENGI` int(11) DEFAULT '0',
  `RENK` int(11) DEFAULT '0',
  `RESIM` longblob,
  `RESIM_AD` varchar(20) DEFAULT '',
  `ESKI_RESIM_AD` varchar(20) DEFAULT '',
  `RESIM_YON` int(11) DEFAULT '32',
  `BASLIK_KAY` tinyint(1) DEFAULT '1',
  `ALT_BASLIK_KAY` tinyint(1) DEFAULT '1',
  `YON_BASLIK` tinyint(1) DEFAULT '0',
  `YON_ALT_BASLIK` tinyint(1) DEFAULT '0',
  `HIZ_BASLIK` int(11) DEFAULT '1',
  `HIZ_ALT_BASLIK` int(11) DEFAULT '1',
  `AKTIF` tinyint(1) DEFAULT '1',
  `S_YF1` varchar(50) DEFAULT '',
  `S_YF2` varchar(50) DEFAULT '',
  `S_YF3` varchar(50) DEFAULT '',
  `I_YF1` int(11) DEFAULT NULL,
  `I_YF2` int(11) DEFAULT NULL,
  `I_YF3` int(11) DEFAULT NULL,
  `B_YF` tinyint(1) DEFAULT NULL,
  `TagPreviewHeight` int(11) DEFAULT NULL,
  `TagPreviewWidth` int(11) DEFAULT NULL,
  `TagPreviewTimerInterval` int(11) DEFAULT NULL,
  `TagPreviewZoom` decimal(18,4) DEFAULT NULL,
  `TotalTag` int(11) DEFAULT NULL,
  `MaxTotalTag` int(11) DEFAULT NULL,
  `TagOverFlowPerId` int(11) DEFAULT NULL,
  `TagOverFlowMessage` text,
  `RandevuButonMetni` varchar(150) DEFAULT '',
  `AltButonSuresi` int(11) DEFAULT NULL,
  `WebdenRandevu` tinyint(1) DEFAULT NULL,
  `BeklemeSuresiMetni` text,
  `EtiketSifirlamasifresi` int(11) DEFAULT NULL,
  `BarkodlaEtiket` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`KID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER DATABASE `kiosk_ayar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;