CREATE TABLE IF NOT EXISTS `molalar` (
  `MID` int(11) NOT NULL AUTO_INCREMENT,
  `PID` int(11) DEFAULT NULL,
  `BAS_TARIH` datetime DEFAULT NULL,
  `BIT_TARIH` datetime DEFAULT NULL,
  `MOLADA` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`MID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
ALTER DATABASE `molalar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;