CREATE TABLE IF NOT EXISTS `oturumlar` (
  `OID` int(11) NOT NULL AUTO_INCREMENT,
  `PID` int(11) NOT NULL,
  `OTURUM_BAS_TARIH` datetime DEFAULT NULL,
  `OTURUM_BIT_TARIH` datetime DEFAULT NULL,
  PRIMARY KEY (`OID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER DATABASE `oturumlar` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;