CREATE TABLE IF NOT EXISTS `servis_hareket` (
  `SKID` int(11) NOT NULL AUTO_INCREMENT,
  `TID` int(11) DEFAULT NULL,
  `SEBEP` varchar(250) DEFAULT '',
  `KAP_TAR` datetime DEFAULT NULL,
  `AC_TAR` datetime DEFAULT NULL,
  `KAPALI` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`SKID`)
) ENGINE=InnoDB AUTO_INCREMENT=63 DEFAULT CHARSET=utf8;
ALTER DATABASE `servis_hareket` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;