CREATE TABLE IF NOT EXISTS `sys_mesaj_master` (
  `SMMID` int(11) NOT NULL AUTO_INCREMENT,
  `MESAJ_TIP` varchar(20) DEFAULT '',
  PRIMARY KEY (`SMMID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER DATABASE `sys_mesaj_master` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;