CREATE TABLE IF NOT EXISTS `terminal_grup` (
  `TGID` int(11) NOT NULL AUTO_INCREMENT,
  `TID` int(11) DEFAULT NULL,
  `GRPID` int(11) DEFAULT NULL,
  `CAGRI_ORAN` smallint(6) DEFAULT NULL,
  `TRANSFER_ORAN` smallint(6) DEFAULT NULL,
  `YARDIM_GRUBU` tinyint(1) DEFAULT NULL,
  `CAGRILAN` smallint(6) DEFAULT '0',
  `TRANSFER_CAGRILAN` smallint(6) DEFAULT '0',
  `ONCELIK` smallint(6) DEFAULT '0',
  `S_YF1` varchar(50) DEFAULT '',
  `S_YF2` varchar(50) DEFAULT '',
  `S_YF3` varchar(50) DEFAULT '',
  `I_YF1` int(11) DEFAULT NULL,
  `I_YF2` int(11) DEFAULT NULL,
  `I_YF3` int(11) DEFAULT NULL,
  `B_YF` tinyint(1) DEFAULT NULL,
  `AYRICALIKLI` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`TGID`)
) ENGINE=InnoDB AUTO_INCREMENT=1152 DEFAULT CHARSET=utf8;
ALTER DATABASE `terminal_grup` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;