CREATE TABLE TERMINAL_BIRIM(
	`id` int AUTO_INCREMENT NOT NULL,
	`BirimNo` int NULL,
	`TerminalID` int NULL,
 CONSTRAINT `PK_TERMINAL_BIRIM` PRIMARY KEY 
(
	`id` ASC
) 
);
ALTER DATABASE `TERMINAL_BIRIM` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

