<?php
$EkranNo='0';
$UstBaslik='OMES LCD UST BASLIK';
$AltBaslik='OMES LCD ALT BASLIK';
$VideoURL='';
$SesURL='';
$PORT_Gonderici='505';
$PORT_Alici='506';
$DefaultFormID='';
$AnatabloID='130'; //BeklemeListesiSet.php 
$ClientIP='';
$OtoIP='';
$KayanYaziFont='Arial';
$KayanYaziPunto='36';
$KayanYaziRenk='4294704909';
$KayanYaziArkaPlanRenk='814625';
$Sutun1='Biletler';
$Sutun2='Vezne';
$SutunRenk='16723712';
$SutunYaziOzellik='regular'; // italic,  regular cagrilar için başlık stili
$SutunYaziKalinlik='100'; // 100-900
$LCDArkaplanRenk='0';
$UstBaslikKaysin='';
$AltBaslikKaysin='true';
$UstBaslikYon='0';
$AltBaslikYon='1';
$UstBaslikHiz='10';
$AltBaslikHiz='10';
$LCDFormArkaplanRenk='2097095';
$CagNoFont='Arial';
$CagNoRenk='16753165';
$CagNoPunto='60';
$SaatYukseklik='';
$TvKaynak='Yok';
$TvKaynakIndex='';
$TvKanal='';
$ServerIP='ekomurcu';
$MediaTipi='4';
$WebBrowserUrl='http://omes.net/';
$CagNoPuntoTekSatir='36';
$Ses='Dosyadan';
$SatirSayisi='7';
$dbUserName='root';
$dbPassword='nichtwar';
$dbName='qcu';
//..........ertu
$bekleyenler_metni='BEKLEYENLER';
$biletno_metni='Bilet NO';
$bekleyenFont='Arial';
$bekleyenPunto='30';
$bekleyenRenk='13631485';
$bekleyenArkaPlanRenk='13696837';
$saatFont='Arial';
$saatPunto='36';
$saatRenk='3602240';
$saatArkaplanRenk='814625';
$SutunPunto='34';
$SutunFont='Arial';
$SutunArkaplanRenk='0';
$animasyonDurum='false';
$animasyonRenk='16776698';
$animasyonArkaplanRenk='16725256';
$animasyonSure='500';
$sayfaYinelemeSuresi='6000';

?>