namespace QVU.WFroms {
    partial class WPrinterSetup {
                                private System.ComponentModel.IContainer components = null;

                                        protected override void Dispose( bool disposing ) {
            if ( disposing && ( components != null ) ) {
                components.Dispose();
            }
            base.Dispose( disposing );
        }

        #region Windows Form Designer generated code

                                        private void InitializeComponent() {
			this.components = new System.ComponentModel.Container();
			this.LstBxPrinterList = new System.Windows.Forms.ListBox();
			this.panel1 = new System.Windows.Forms.Panel();
			this.panel2 = new System.Windows.Forms.Panel();
			this.LblResultAndReason = new System.Windows.Forms.Label();
			this.pictureBox1 = new System.Windows.Forms.PictureBox();
			this.BtnPrintSave = new System.Windows.Forms.Button();
			this.LblCurrentPrinter = new System.Windows.Forms.Label();
			this.LblPrinterName = new System.Windows.Forms.Label();
			this.label10 = new System.Windows.Forms.Label();
			this.label1 = new System.Windows.Forms.Label();
			this.label6 = new System.Windows.Forms.Label();
			this.label4 = new System.Windows.Forms.Label();
			this.label3 = new System.Windows.Forms.Label();
			this.label8 = new System.Windows.Forms.Label();
			this.label7 = new System.Windows.Forms.Label();
			this.label2 = new System.Windows.Forms.Label();
			this.label9 = new System.Windows.Forms.Label();
			this.label5 = new System.Windows.Forms.Label();
			this.TmrCloseWait = new System.Windows.Forms.Timer(this.components);
			this.panel1.SuspendLayout();
			this.panel2.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
			this.SuspendLayout();
												this.LstBxPrinterList.Dock = System.Windows.Forms.DockStyle.Fill;
			this.LstBxPrinterList.Font = new System.Drawing.Font("Calibri", 12F);
			this.LstBxPrinterList.FormattingEnabled = true;
			this.LstBxPrinterList.HorizontalScrollbar = true;
			this.LstBxPrinterList.ItemHeight = 19;
			this.LstBxPrinterList.Location = new System.Drawing.Point(0, 0);
			this.LstBxPrinterList.Margin = new System.Windows.Forms.Padding(4);
			this.LstBxPrinterList.Name = "LstBxPrinterList";
			this.LstBxPrinterList.Size = new System.Drawing.Size(268, 329);
			this.LstBxPrinterList.TabIndex = 0;
			this.LstBxPrinterList.SelectedIndexChanged += new System.EventHandler(this.LstBxPrinterList_SelectedIndexChanged);
			this.LstBxPrinterList.DoubleClick += new System.EventHandler(this.LstBxPrinterList_DoubleClick);
												this.panel1.Controls.Add(this.LstBxPrinterList);
			this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel1.Location = new System.Drawing.Point(0, 0);
			this.panel1.Margin = new System.Windows.Forms.Padding(4);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(268, 329);
			this.panel1.TabIndex = 1;
												this.panel2.Controls.Add(this.LblResultAndReason);
			this.panel2.Controls.Add(this.pictureBox1);
			this.panel2.Controls.Add(this.BtnPrintSave);
			this.panel2.Controls.Add(this.LblCurrentPrinter);
			this.panel2.Controls.Add(this.LblPrinterName);
			this.panel2.Controls.Add(this.label10);
			this.panel2.Controls.Add(this.label1);
			this.panel2.Controls.Add(this.label6);
			this.panel2.Controls.Add(this.label4);
			this.panel2.Controls.Add(this.label3);
			this.panel2.Controls.Add(this.label8);
			this.panel2.Controls.Add(this.label7);
			this.panel2.Controls.Add(this.label2);
			this.panel2.Controls.Add(this.label9);
			this.panel2.Controls.Add(this.label5);
			this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
			this.panel2.Location = new System.Drawing.Point(268, 0);
			this.panel2.Margin = new System.Windows.Forms.Padding(4);
			this.panel2.Name = "panel2";
			this.panel2.Size = new System.Drawing.Size(289, 329);
			this.panel2.TabIndex = 2;
												this.LblResultAndReason.AutoSize = true;
			this.LblResultAndReason.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.LblResultAndReason.Location = new System.Drawing.Point(11, 299);
			this.LblResultAndReason.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.LblResultAndReason.Name = "LblResultAndReason";
			this.LblResultAndReason.Size = new System.Drawing.Size(0, 19);
			this.LblResultAndReason.TabIndex = 7;
												this.pictureBox1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
			this.pictureBox1.Image = global::QVU.Properties.Resources.PrinterSetup;
			this.pictureBox1.Location = new System.Drawing.Point(157, 3);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new System.Drawing.Size(128, 128);
			this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pictureBox1.TabIndex = 6;
			this.pictureBox1.TabStop = false;
												this.BtnPrintSave.Enabled = false;
			this.BtnPrintSave.Font = new System.Drawing.Font("Calibri", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.BtnPrintSave.Location = new System.Drawing.Point(157, 258);
			this.BtnPrintSave.Margin = new System.Windows.Forms.Padding(4);
			this.BtnPrintSave.Name = "BtnPrintSave";
			this.BtnPrintSave.Size = new System.Drawing.Size(128, 37);
			this.BtnPrintSave.TabIndex = 5;
			this.BtnPrintSave.Text = "Kaydet";
			this.BtnPrintSave.UseVisualStyleBackColor = true;
			this.BtnPrintSave.Click += new System.EventHandler(this.BtnPrintSave_Click);
												this.LblCurrentPrinter.AutoSize = true;
			this.LblCurrentPrinter.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.LblCurrentPrinter.ForeColor = System.Drawing.Color.SteelBlue;
			this.LblCurrentPrinter.Location = new System.Drawing.Point(11, 182);
			this.LblCurrentPrinter.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.LblCurrentPrinter.Name = "LblCurrentPrinter";
			this.LblCurrentPrinter.Size = new System.Drawing.Size(0, 19);
			this.LblCurrentPrinter.TabIndex = 4;
												this.LblPrinterName.AutoSize = true;
			this.LblPrinterName.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.LblPrinterName.ForeColor = System.Drawing.Color.LightSkyBlue;
			this.LblPrinterName.Location = new System.Drawing.Point(11, 231);
			this.LblPrinterName.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.LblPrinterName.Name = "LblPrinterName";
			this.LblPrinterName.Size = new System.Drawing.Size(0, 19);
			this.LblPrinterName.TabIndex = 4;
												this.label10.AutoSize = true;
			this.label10.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label10.Location = new System.Drawing.Point(193, 163);
			this.label10.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label10.Name = "label10";
			this.label10.Size = new System.Drawing.Size(13, 19);
			this.label10.TabIndex = 4;
			this.label10.Text = ":";
												this.label1.AutoSize = true;
			this.label1.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label1.Location = new System.Drawing.Point(193, 212);
			this.label1.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label1.Name = "label1";
			this.label1.Size = new System.Drawing.Size(13, 19);
			this.label1.TabIndex = 4;
			this.label1.Text = ":";
												this.label6.AutoSize = true;
			this.label6.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label6.Location = new System.Drawing.Point(7, 45);
			this.label6.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label6.Name = "label6";
			this.label6.Size = new System.Drawing.Size(132, 36);
			this.label6.TabIndex = 4;
			this.label6.Text = "kurulu olan yazıcılar \r\nlistelenmektedir.";
												this.label4.AutoSize = true;
			this.label4.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label4.Location = new System.Drawing.Point(7, 27);
			this.label4.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label4.Name = "label4";
			this.label4.Size = new System.Drawing.Size(125, 18);
			this.label4.TabIndex = 4;
			this.label4.Text = "bilgisayar üzerinde";
												this.label3.AutoSize = true;
			this.label3.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label3.Location = new System.Drawing.Point(7, 9);
			this.label3.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label3.Name = "label3";
			this.label3.Size = new System.Drawing.Size(91, 18);
			this.label3.TabIndex = 4;
			this.label3.Text = "Yan tarafta bu";
												this.label8.AutoSize = true;
			this.label8.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label8.Location = new System.Drawing.Point(7, 133);
			this.label8.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label8.Name = "label8";
			this.label8.Size = new System.Drawing.Size(266, 18);
			this.label8.TabIndex = 4;
			this.label8.Text = "olan varsayılan yazıcıyı bu listeden seçiniz.";
												this.label7.AutoSize = true;
			this.label7.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label7.Location = new System.Drawing.Point(7, 115);
			this.label7.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label7.Name = "label7";
			this.label7.Size = new System.Drawing.Size(150, 18);
			this.label7.TabIndex = 4;
			this.label7.Text = "yazdırırken kullanılacak";
												this.label2.AutoSize = true;
			this.label2.Font = new System.Drawing.Font("Calibri", 11F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label2.Location = new System.Drawing.Point(7, 97);
			this.label2.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label2.Name = "label2";
			this.label2.Size = new System.Drawing.Size(71, 18);
			this.label2.TabIndex = 4;
			this.label2.Text = "Fiktif bilet";
												this.label9.AutoSize = true;
			this.label9.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label9.Location = new System.Drawing.Point(11, 163);
			this.label9.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label9.Name = "label9";
			this.label9.Size = new System.Drawing.Size(168, 19);
			this.label9.TabIndex = 4;
			this.label9.Text = "Mevcut Varsayılan Yazıcı";
												this.label5.AutoSize = true;
			this.label5.Font = new System.Drawing.Font("Calibri", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.label5.Location = new System.Drawing.Point(11, 212);
			this.label5.Margin = new System.Windows.Forms.Padding(7, 0, 7, 0);
			this.label5.Name = "label5";
			this.label5.Size = new System.Drawing.Size(83, 19);
			this.label5.TabIndex = 4;
			this.label5.Text = "Seçili Yazıcı";
												this.TmrCloseWait.Interval = 50;
			this.TmrCloseWait.Tick += new System.EventHandler(this.TmrCloseWait_Tick);
												this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.ClientSize = new System.Drawing.Size(557, 329);
			this.Controls.Add(this.panel2);
			this.Controls.Add(this.panel1);
			this.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(162)));
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
			this.KeyPreview = true;
			this.Margin = new System.Windows.Forms.Padding(4);
			this.Name = "WPrinterSetup";
			this.ShowInTaskbar = false;
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
			this.Text = "Sanal Terminal Fiktif Bilet Yazıcı Seçim Penceresi";
			this.TopMost = true;
			this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.WPrinterSetup_FormClosing);
			this.Load += new System.EventHandler(this.WPrinterSetup_Load);
			this.KeyDown += new System.Windows.Forms.KeyEventHandler(this.WPrinterSetup_KeyDown);
			this.panel1.ResumeLayout(false);
			this.panel2.ResumeLayout(false);
			this.panel2.PerformLayout();
			((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
			this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListBox LstBxPrinterList;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Button BtnPrintSave;
        private System.Windows.Forms.Label LblPrinterName;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label LblCurrentPrinter;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.Timer TmrCloseWait;
        private System.Windows.Forms.Label LblResultAndReason;
    }
}
