USE [QCU2.MDF]
GO

/****** Object:  Table [dbo].[ANKET]    Script Date: 7.06.2018 22:25:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ANKET](
	[SatirId] [int] IDENTITY(1,1) NOT NULL,
	[Secim] [int] NULL,
	[Tarih] [datetime] NULL,
	[TerminalId] [int] NULL,
 CONSTRAINT [PK_ANKET] PRIMARY KEY CLUSTERED 
(
	[SatirId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


