USE [QCU2.MDF]
GO

/****** Object:  Table [dbo].[FONTLAR]    Script Date: 7.06.2018 22:28:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FONTLAR](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[FONT] [nvarchar](100) NULL,
 CONSTRAINT [PK_FONTLAR] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

