USE [QCU2.MDF]
GO

/****** Object:  Table [dbo].[MOLALAR]    Script Date: 7.06.2018 22:30:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOLALAR](
	[MID] [int] IDENTITY(1,1) NOT NULL,
	[PID] [int] NULL,
	[BAS_TARIH] [datetime] NULL,
	[BIT_TARIH] [datetime] NULL,
	[MOLADA] [bit] NULL,
 CONSTRAINT [PK_MOLALAR] PRIMARY KEY CLUSTERED 
(
	[MID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[MOLALAR] ADD  CONSTRAINT [DF_MOLALAR_MOLADA]  DEFAULT ((0)) FOR [MOLADA]
GO

