USE [QCU2.MDF]
GO

/****** Object:  Table [dbo].[SISTEM_CONFIG]    Script Date: 7.06.2018 22:33:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SISTEM_CONFIG](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SERVER_IP] [nvarchar](15) NULL,
	[FIRMA_ISMI] [nvarchar](50) NULL,
	[KioskId] [int] NULL,
 CONSTRAINT [PK_Table_1] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

