USE [QCU2.MDF]
GO

/****** Object:  Table [dbo].[TERMINAL_BIRIM]    Script Date: 7.06.2018 22:35:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TERMINAL_BIRIM](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[BirimNo] [int] NULL,
	[TerminalID] [int] NULL,
 CONSTRAINT [PK_TERMINAL_BIRIM] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

